// Code generated by `mygo generate`. DO NOT EDIT.

import { call, type Channel } from "mygo-runtime";

// ---- Types ----

/**
 * FMField is one key of the frontmatter, in the order the file has them.
 * Value is an FMValue.
 */
export interface FMField {
  key: string;
  value: FMValue;
}

/** FMValue is a YAML value: a scalar, a list or a map. */
export interface FMValue {
  /** "scalar" | "list" | "map" */
  type: string;
  value?: string;
  /** str, bool, int, float, null, timestamp */
  tag?: string;
  items?: FMValue[];
  fields?: FMField[];
}

/** FileContent is a file of a skill. */
export interface FileContent {
  path: string;
  size: number;
  text: string;
  binary: boolean;
  truncated: boolean;
}

/** FileEntry is a file or folder inside a skill. */
export interface FileEntry {
  path: string;
  dir: boolean;
  size: number;
}

/** GitInfo describes the repository a linked skill lives in. */
export interface GitInfo {
  root: string;
  origin?: string;
  branch?: string;
  lastCommit?: string;
  lastDate?: string;
  lastTitle?: string;
  dirty: string[];
}

/** Library is the scanned skills directory. */
export interface Library {
  root: string;
  exists: boolean;
  lock?: LockInfo;
  skills: Skill[];
  snapshot?: SnapshotInfo;
  updates?: UpdateReport;
  /** RemovedSinceSnapshot lists skills the snapshot had that are gone. */
  removedSinceSnapshot: string[];
  scannedAt: string;
}

/**
 * LockEntry is one skill recorded by the `skills` CLI (vercel-labs/skills),
 * either in the global ~/.agents/.skill-lock.json (skillFolderHash) or in a
 * project's skills-lock.json (computedHash).
 */
export interface LockEntry {
  source: string;
  sourceType: string;
  sourceUrl?: string;
  ref?: string;
  skillPath?: string;
  skillFolderHash?: string;
  computedHash?: string;
  pluginName?: string;
  installedAt?: string;
  updatedAt?: string;
}

/** LockInfo describes the lock file found for a skills directory. */
export interface LockInfo {
  path: string;
  /** "global" (.skill-lock.json) or "project" (skills-lock.json) */
  kind: string;
  version: number;
  count: number;
}

/** Skill summarizes one skill for the sidebar. */
export interface Skill {
  /** ID is the folder name in the skills directory. */
  id: string;
  name: string;
  description: string;
  kind: SkillKind;
  /**
   * Group is the skill group key: the source repository ("owner/repo",
   * "host/owner/repo"), or "local" for unmanaged folders.
   */
  group: string;
  /**
   * SubGroup is the category inside the source, from the folder that holds
   * the skill in its repository (e.g. "engineering" for
   * skills/engineering/tdd/SKILL.md), or the lock's pluginName.
   */
  subGroup?: string;
  version?: string;
  tags: string[];
  linkTarget?: string;
  lock?: LockEntry;
  /** LocalHash is the git tree hash of the folder as it is on disk. */
  localHash?: string;
  /**
   * Integrity compares the folder with the hash the lock recorded:
   * "match", "differs" or "" when there is nothing to compare.
   */
  integrity?: string;
  /**
   * Snapshot compares the folder with the last local index snapshot:
   * "new", "changed", "same" or "" without a snapshot.
   */
  snapshot?: string;
  fileCount: number;
  modified?: string;
  hasSkillMd: boolean;
  error?: string;
}

/** SkillDetail is everything the reader shows for one skill. */
export interface SkillDetail {
  skill: Skill;
  path: string;
  realPath: string;
  frontmatter: FMField[];
  frontmatterRaw: string;
  frontmatterError?: string;
  body: string;
  files: FileEntry[];
  git?: GitInfo;
}

/** SkillKind tells how a skill got into the directory. */
export type SkillKind = "installed" | "linked" | "local" | "missing";

/**
 * SnapshotInfo describes the local index snapshot of a skills directory: the
 * git tree hash of every skill folder at the time it was taken. It is this
 * app's own index, kept in its data directory, and catches changes to every
 * skill, including the ones no lock file tracks.
 */
export interface SnapshotInfo {
  takenAt: string;
  count: number;
  changed: number;
  added: number;
  removed: number;
  path: string;
}

/** UpdateProgress is streamed while a check runs. */
export interface UpdateProgress {
  done: number;
  total: number;
  source: string;
}

/** UpdateReport is the result of a whole check, saved between runs. */
export interface UpdateReport {
  checkedAt: string;
  results: Record<string, UpdateResult>;
  outdated: number;
  errors: number;
  checked: number;
}

/** UpdateResult is the check of one skill. */
export interface UpdateResult {
  id: string;
  source: string;
  status: UpdateStatus;
  lockHash?: string;
  remoteHash?: string;
  /** "gh api", "github api", "git clone" */
  via?: string;
  message?: string;
}

/** UpdateStatus is the result of checking one skill against its source. */
export type UpdateStatus = "current" | "outdated" | "gone" | "error" | "skipped";

// ---- Services ----

/** Skills reads a skills directory (by default ~/.agents/skills) for the page. */
export const Skills = {
  /**
   * CheckUpdates compares the lock file's folder hashes with the sources,
   * streaming progress per source repository.
   */
  checkUpdates(root: string, progress: Channel<UpdateProgress>): Promise<UpdateReport | null> {
    return call("Skills.CheckUpdates", root, progress);
  },
  /** DefaultRoot returns the default skills directory, ~/.agents/skills. */
  defaultRoot(): Promise<string> {
    return call("Skills.DefaultRoot");
  },
  /** OpenExternal opens an http(s) URL in the default browser. */
  openExternal(url: string): Promise<void> {
    return call("Skills.OpenExternal", url);
  },
  /** PickRoot asks for another skills directory; "" when canceled. */
  pickRoot(current: string): Promise<string> {
    return call("Skills.PickRoot", current);
  },
  /** Read returns the frontmatter, Markdown body and files of one skill. */
  read(root: string, id: string): Promise<SkillDetail | null> {
    return call("Skills.Read", root, id);
  },
  /** ReadFile returns a file inside a skill folder, as text when it is text. */
  readFile(root: string, id: string, path: string): Promise<FileContent | null> {
    return call("Skills.ReadFile", root, id, path);
  },
  /** Reveal shows a path in Finder. */
  reveal(path: string): Promise<void> {
    return call("Skills.Reveal", path);
  },
  /**
   * Scan lists every skill of root ("" for the default) with its group, lock
   * entry, integrity against the lock, and state against the local snapshot.
   */
  scan(root: string): Promise<Library | null> {
    return call("Skills.Scan", root);
  },
  /** TakeSnapshot records the current hash of every skill as the local index. */
  takeSnapshot(root: string): Promise<Library | null> {
    return call("Skills.TakeSnapshot", root);
  },
} as const;
